apiVersion: v1
kind: Service
metadata:
  name: mutating-registry-webhook
  labels:
    app: mutating-registry-webhook
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    app: mutating-registry-webhook
