name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ github.ref_name }}
      push_image: true
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
  release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            registry-mutation-webhook-*.tgz
          name: Release ${{ env.VERSION }}
          generate_release_notes: true
          labels: ${{ steps.meta.outputs.labels }}
