name: Test Build

on:
  pull_request:
    branches:
      - main

jobs:
  get-latest-tag:
    uses: ./.github/workflows/get-latest-tag.yaml

  test-build:
    needs: [get-latest-tag]
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ needs.get-latest-tag.outputs.next_pre_version }}
      push_image: ${{ !github.event.pull_request.draft }}
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}

  cleanup-old-releases:
    uses: ./.github/workflows/cleanup-old-releases.yaml
    with:
      retention_days: 7
      repository: ${{ github.repository }}
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}

  # package-helm:
  #   needs: [get-latest-tag, test-build]
  #   if: ${{ !github.event.pull_request.draft }}
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Set up Helm
  #       uses: azure/setup-helm@v3
  #       with:
  #         version: v3.12.0

  #     - name: Package Helm chart
  #       run: |
  #         helm package ./charts --version ${{ needs.get-latest-tag.outputs.next_pre_version }}

  #     - name: Create GitHub Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         name: Test ${{ needs.get-latest-tag.outputs.next_pre_version }}
  #         files: registry-mutation-webhook-*.tgz
  #         tag_name: ${{ needs.get-latest-tag.outputs.next_pre_version }}
  #         prerelease: true
  #         generate_release_notes: false